
drop database if exists battle_buddies_db;

use battle_buddies_db;
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'admin', 'cwhitloe0@kickstarter.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'izzy', 'veye1@printfriendly.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'bridget', 'crudiger2@vk.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'dani', 'mpellatt3@themeforest.net',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'vdunbar4', 'oharrowsmith4@marriott.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'dgirardi5', 'areignard5@xing.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'ofrye6', 'susher6@state.gov', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'naspinall7', 'emartyn7@free.fr', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.', 'cogers8', 'druoss8@netscape.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mghelardoni9', 'koylett9@cnbc.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'athornthwaitea', 'kduckita@smugmug.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'gwakerb', 'jdulakeb@domainmarket.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'pkivlinc', 'hmutlowc@weebly.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mbroschekd', 'ngrigolashvilld@hhs.gov', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'gwernhere', 'nchaldecotte@nps.gov',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mwalbyf', 'mrowanf@sakura.ne.jp', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'rofarrisg', 'cwhordleyg@shareasale.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mapplinh', 'fteeseh@biglobe.ne.jp', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'jdarguei', 'qpirronei@google.com.hk', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'tbouldsj', 'hbalfourj@plala.or.jp',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'lstoodersk', 'roheagertiek@cornell.edu', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'ddoretl', 'eviolletl@purevolume.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'abrookm', 'hgrimestonem@wordpress.org', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'tshaklen', 'habramovitzn@squarespace.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mhatto', 'jstlouiso@purevolume.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'rsearsp', 'hjantzenp@sourceforge.net', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mgallerq', 'mmoodeyq@imdb.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'amorotr', 'whampsteadr@bizjournals.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'bbeckitts', 'dspreckleys@elegantthemes.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'balesbrookt', 'sdigglest@goo.ne.jp', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mwainu', 'rmillisu@nasa.gov', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'akleehuhlerv', 'mformanv@4shared.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'bameerbegw', 'iestickw@acquirethisname.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'cgallihawkx', 'bapplewhitex@mit.edu',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'hdjordjevicy', 'imatuszinskiy@imageshack.us',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'hskeemerz', 'fropertz@mlb.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'kcantillion10', 'sshrubshall10@bluehost.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'fkerrigan11', 'aelger11@desdev.cn',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'ngoodricke12', 'dludron12@last.fm', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'amatuszyk13', 'nshemelt13@alibaba.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'clytell14', 'ofairbank14@disqus.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'fitscowics15', 'cpenhall15@tinypic.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'cabramowsky16', 'aprantoni16@usnews.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'rbullon17', 'lpiwell17@instagram.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'myanov18', 'dbakewell18@upenn.edu',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'ahaddrill19', 'mflintoff19@deliciousdays.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'dimason1a', 'pmatelaitis1a@freewebs.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'emuro1b', 'amorch1b@google.com.br',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'kchesswas1c', 'pmacfall1c@oakley.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'afletcher1d', 'rcovey1d@friendfeed.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'rnewart1e', 'gaugustine1e@biglobe.ne.jp',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'cwaliszewski1f', 'bquilkin1f@booking.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'umcelrath1g', 'kleathe1g@acquirethisname.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'lcarter1h', 'zhaslen1h@dailymail.co.uk', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'ahaughton1i', 'emcgourty1i@blogs.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'eknighton1j', 'tcollelton1j@ocn.ne.jp',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'vtantrum1k', 'rtreske1k@usa.gov',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'iskerrett1l', 'epigne1l@elpais.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'rsivewright1m', 'igrimmer1m@mail.ru', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'lklimschak1n', 'barmytage1n@seesaa.net', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'fcomber1o', 'amaple1o@nih.gov', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'esmowton1p', 'hmccoole1p@exblog.jp', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'ghampton1q', 'lellerbeck1q@amazonaws.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'criguard1r', 'ktreweela1r@dot.gov',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'dbartley1s', 'bgethouse1s@wufoo.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'jharesign1t', 'hfrostdicke1t@cam.ac.uk', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'wlyle1u', 'pslack1u@apple.com', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'koliphard1v', 'bogus1v@printfriendly.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'sfindley1w', 'ljennaway1w@telegraph.co.uk',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'fhuske1x', 'jambrosi1x@zdnet.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'xdanby1y', 'rmanus1y@yahoo.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'yhugill1z', 'mlesmonde1z@livejournal.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'lkener20', 'kstorror20@last.fm',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'adrake21', 'cwhines21@weibo.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'rgartshore22', 'tkaley22@hubpages.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'hragg23', 'trobardet23@stumbleupon.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'sfishbourn24', 'mohearn24@house.gov',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'fmillichip25', 'ghoofe25@tinyurl.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'lmangon26', 'lwroath26@aol.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'ghunnaball27', 'ahadcock27@storify.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'cnellen28', 'tvere28@discuz.net',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'hdye29', 'nrawle29@businessinsider.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'pduckhouse2a', 'jleile2a@cyberchimps.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mhughs2b', 'bmanterfield2b@sfgate.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'chellsdon2c', 'gpendreigh2c@skyrock.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'bminor2d', 'gmessom2d@bizjournals.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'rhynson2e', 'causiello2e@unesco.org',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'hjakeman2f', 'ihartil2f@barnesandnoble.com', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'jwatchorn2g', 'anuss2g@webmd.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'lbusch2h', 'abellringer2h@smugmug.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'rsrawley2i', 'cshuker2i@wordpress.org', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mnewlove2j', 'fthurborn2j@google.co.uk', true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'hoveral2k', 'msneesbie2k@dot.gov',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'usteptow2l', 'mbuie2l@hatena.ne.jp',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'schaplyn2m', 'dbrambell2m@msn.com',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'acharlson2n', 'fdavidovics2n@jugem.jp', false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'jskeffington2o', 'ahowsan2o@trellian.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mfencott2p', 'edugall2p@dion.ne.jp',  true);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'thalstead2q', 'oplanke2q@barnesandnoble.com',  false);
insert into users (password,  username, email,  is_admin) values ( '$2a$10$DRibzeKQLUtnTOF5nCnnMegxRg0Tu4hLrVLX0u1L9QCbFZkiGtSS.',  'mmonsey2r', 'mfalconertaylor2r@howstuffworks.com', false);


insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Male', 'Gayla', 'Hedgecock', '1993-06-14', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Army', 'O6', true, true, 1);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Female', 'Olympie', 'Jurries', '1989-02-25', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Air force', 'O9', false, false, 2);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Female', 'Obadias', 'Goby', '1993-04-28', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Navy', 'E6', false, false, 3);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Male', 'Goldarina', 'Perrinchief', '1992-03-07', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Marine Corps', 'E9', false, false, 4);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Female', 'Hans', 'Clay', '2001-03-01', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Navy', 'E8', false, true, 5);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Female', 'Garold', 'Spark', '2002-01-28', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Coast Guard', 'E2', false, false, 6);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Female', 'Darb', 'Boncore', '1987-02-12', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Coast Guard', 'E3', false, false, 7);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Male', 'Eugen', 'Thomazet', '1990-09-07', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Coast Guard', 'E6', true, false, 8);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Female', 'Zsazsa', 'Haslen', '1985-08-28', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Navy', 'E5', true, true, 9);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Calvin', 'Muggach', '1990-07-29', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Navy', 'O10', false, true, 10);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Ricard', 'Bull', '1994-05-15', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Army', 'E9', true, false, 11);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Danice', 'Royston', '1998-12-06', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Navy', 'E1', false, true, 12);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Gregorius', 'Oventon', '1990-01-16', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Air force', 'E5', true, false, 13);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Dory', 'Edgeller', '2001-08-28', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Army', 'O1', false, true, 14);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Aura', 'Safont', '2000-09-22', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Navy', 'O2', true, true, 15);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Nona', 'Ruffey', '1993-02-26', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Marine Corps', 'O1', false, false, 16);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Jena', 'Maymond', '2000-09-10', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Air force', 'O3', true, false, 17);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Arni', 'Flexman', '1996-04-13', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Marine Corps', 'E9', true, false, 18);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Urbain', 'Hardes', '1985-06-15', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Army', 'O3', true, true, 19);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Garth', 'Yeldham', '1996-03-14', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Coast Guard', 'O6', false, true, 20);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Felicdad', 'Livzey', '1994-01-23', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Marine Corps', 'E9', false, true, 21);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Sandy', 'Bosche', '1991-04-08', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Coast Guard', 'E7', false, true, 22);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Guillemette', 'Gollin', '1988-08-24', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Air force', 'E7', false, true, 23);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Rolf', 'Jeaneau', '1995-08-30', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Marine Corps', 'E4', true, true, 24);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Harriette', 'Noton', '1992-11-14', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Coast Guard', 'E4', false, true, 25);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Rickie', 'Jacklin', '1983-08-29', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Navy', 'E1', false, false, 26);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Neddie', 'Coady', '1988-02-29', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Navy', 'O8', false, true, 27);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Chester', 'Minster', '1989-08-28', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Army', 'E3', true, true, 28);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Yuri', 'Snelgar', '1986-06-29', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Coast Guard', 'O7', false, false, 29);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Pippo', 'Egan', '1988-03-19', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Air force', 'E8', false, false, 30);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Gweneth', 'Blasing', '1991-02-19', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Marine Corps', 'E9', true, true, 31);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Annalee', 'Muslim', '1994-08-13', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Army', 'E9', false, false, 32);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Domenic', 'Pranger', '1988-12-10', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Army', 'E7', true, true, 33);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Karole', 'Morhall', '1986-08-24', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Marine Corps', 'E6', true, true, 34);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Jamima', 'Kays', '1994-02-26', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Coast Guard', 'O4', false, true, 35);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Adam', 'Kimbrough', '1990-07-16', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Marine Corps', 'O7', true, false, 36);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Elise', 'Olkowicz', '1983-12-17', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Marine Corps', 'E8', true, false, 37);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Ernesto', 'Arzu', '1985-05-23', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Air force', 'E1', true, true, 38);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Jimmie', 'Westhoff', '1993-03-03', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Army', 'E3', false, true, 39);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Myrlene', 'Girardet', '1997-10-12', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Air force', 'E6', true, false, 40);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Zenia', 'Kilshall', '2002-06-23', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Coast Guard', 'O7', false, true, 41);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Mohandas', 'Jestico', '1996-07-09', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Marine Corps', 'O9', false, true, 42);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Stavro', 'Silson', '1988-05-06', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Air force', 'O3', true, false, 43);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Antonetta', 'Capponeer', '1984-06-28', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Marine Corps', 'O2', true, false, 44);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Man', 'Gaspero', '1995-04-21', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Marine Corps', 'E2', false, true, 45);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Gothart', 'Kettle', '1990-04-29', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Navy', 'O6', false, false, 46);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Kristen', 'Scones', '1997-01-01', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Army', 'E6', false, true, 47);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Toma', 'Birkmyre', '1980-12-23', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Air force', 'E3', false, false, 48);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Hesther', 'Quinton', '2000-05-30', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Air force', 'O5', true, true, 49);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Tarah', 'Habercham', '2000-08-23', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Coast Guard', 'O9', false, true, 50);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Cloe', 'Walden', '1983-05-27', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Army', 'O7', true, false, 51);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Carolyne', 'Messier', '2001-01-29', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Coast Guard', 'E9', true, false, 52);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Garik', 'Folds', '1997-08-19', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Army', 'E2', true, false, 53);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Dotty', 'Mottershaw', '1985-10-16', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Army', 'O2', false, true, 54);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Cobby', 'Joreau', '1986-07-01', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Marine Corps', 'O5', false, true, 55);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Donetta', 'Rugg', '1985-07-26', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Marine Corps', 'O4', true, true, 56);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Thelma', 'Breach', '1987-03-05', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Army', 'O5', true, true, 57);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Marice', 'Binner', '1981-11-17', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Air force', 'O8', true, true, 58);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Berte', 'Millar', '1985-12-25', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 'Coast Guard', 'O5', false, false, 59);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Wendall', 'Kirkbride', '1992-01-21', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Army', 'E2', false, true, 60);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Rea', 'Eddington', '1992-02-29', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Army', 'E3', false, true, 61);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Rosco', 'Revance', '1987-02-24', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Marine Corps', 'E4', false, true, 62);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Priscella', 'Marjoram', '1986-05-20', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Navy', 'O1', true, false, 63);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Alikee', 'Claris', '1980-12-25', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Air force', 'O3', true, false, 64);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Kennie', 'Dabs', '2001-12-01', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Army', 'O3', true, false, 65);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Rance', 'Bocking', '1992-11-16', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Air force', 'E9', false, false, 66);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Marcelline', 'Crowne', '1984-04-10', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Marine Corps', 'E2', false, true, 67);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Gerry', 'Ivkovic', '1995-04-06', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Army', 'E1', false, false, 68);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Ezekiel', 'Jann', '1989-01-02', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Army', 'O6', false, true, 69);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Shayla', 'Pelchat', '1995-11-25', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Army', 'O7', false, false, 70);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Sam', 'Gumm', '1999-04-01', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Navy', 'O9', false, true, 71);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Sholom', 'Austing', '1996-06-27', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Air force', 'E8', true, false, 72);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Davin', 'O''Dougherty', '1998-12-24', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Navy', 'O1', false, true, 73);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Bertie', 'Fibbit', '1997-08-28', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Marine Corps', 'E8', true, true, 74);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Koo', 'McGragh', '1989-03-26', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Coast Guard', 'E6', true, false, 75);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Angelique', 'Bavridge', '1987-08-27', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Marine Corps', 'O4', true, false, 76);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Ettore', 'Gaynesford', '1990-02-15', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Navy', 'E8', false, true, 77);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Sayers', 'Benedetti', '2000-08-08', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Air force', 'O4', false, false, 78);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Karlik', 'Ferroli', '1996-12-12', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'Marine Corps', 'O4', true, false, 79);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Yasmin', 'Pues', '1986-06-03', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Coast Guard', 'E3', false, false, 80);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Kiley', 'Broy', '1984-09-24', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Coast Guard', 'E9', true, false, 81);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Sayers', 'O''Shevlan', '2001-06-06', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Navy', 'E2', true, false, 82);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Douglas', 'Viccars', '2003-08-14', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Army', 'E9', false, false, 83);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Bennie', 'Bradane', '1982-08-08', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Navy', 'E4', false, true, 84);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Wilfred', 'Mogenot', '1985-06-29', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Army', 'O10', false, true, 85);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Ame', 'Reynoldson', '1994-05-12', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Navy', 'O6', false, false, 86);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Amery', 'Toyne', '1988-07-13', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Marine Corps', 'O10', true, false, 87);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Gardiner', 'Guillond', '1987-07-10', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Air force', 'E3', false, true, 88);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Jordon', 'Castelletto', '2003-09-07', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Marine Corps', 'O3', true, false, 89);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female','Robina', 'Woodroofe', '1985-10-31', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Navy', 'E9', false, false, 90);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Sol', 'Pautot', '1987-07-26', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Marine Corps', 'E6', false, false, 91);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Lyndell', 'Becker', '1981-02-09', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Coast Guard', 'O9', true, false, 92);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Salomo', 'Roller', '1997-08-02', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Navy', 'O3', true, false, 93);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Male', 'Moritz', 'Wolfenden', '1998-05-18', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Air force', 'E7', true, false, 94);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Petronia', 'Lubeck', '1998-04-14', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Marine Corps', 'E6', true, false, 95);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Anallese', 'Capron', '1995-08-24', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Army', 'E4', true, true, 96);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Eirena', 'Wyllis', '1998-10-15', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Army', 'E9', true, true, 97);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Valaria', 'Sauvan', '1993-06-13', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Navy', 'E9', true, false, 98);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ('Female', 'Adrianne', 'Kacheller', '2000-01-28', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Coast Guard', 'E6', true, true, 99);
insert into profiles ( gender, first_name, last_name, birth_date, bio, branch, mil_rank, married, mil_spouse, user_id) values ( 'Female', 'Kylie', 'Kitchin', '1989-02-16', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Air force', 'E2', true, true, 100);



insert into children  (birth_date, gender, profile_id) values ('2015-03-07', 'Female', 81);
insert into children  (birth_date, gender, profile_id) values ('2010-06-14', 'Male', 85);
insert into children  (birth_date, gender, profile_id) values ('2016-05-23', 'Female', 19);
insert into children  (birth_date, gender, profile_id) values ('2019-10-18', 'Male', 69);
insert into children  (birth_date, gender, profile_id) values ('2018-11-12', 'Male', 36);
insert into children  (birth_date, gender, profile_id) values ('2019-09-21', 'Male', 97);
insert into children  (birth_date, gender, profile_id) values ('2011-07-20', 'Female', 90);
insert into children  (birth_date, gender, profile_id) values ('2014-03-31', 'Female', 55);
insert into children  (birth_date, gender, profile_id) values ('2012-03-05', 'Female', 76);
insert into children  (birth_date, gender, profile_id) values ( '2017-12-15', 'Male', 12);
insert into children  (birth_date, gender, profile_id) values ( '2014-12-21', 'Male', 7);
insert into children  (birth_date, gender, profile_id) values ( '2017-09-04', 'Female', 75);
insert into children  (birth_date, gender, profile_id) values ( '2010-01-28', 'Male', 25);
insert into children  (birth_date, gender, profile_id) values ( '2014-05-03', 'Female', 64);
insert into children  (birth_date, gender, profile_id) values ( '2017-10-06', 'Female', 66);
insert into children  (birth_date, gender, profile_id) values ( '2013-10-03', 'Female', 32);
insert into children  (birth_date, gender, profile_id) values ( '2015-02-22', 'Male', 1);
insert into children  (birth_date, gender, profile_id) values ( '2015-09-19', 'Female', 19);
insert into children  (birth_date, gender, profile_id) values ( '2018-02-17', 'Female', 76);
insert into children  (birth_date, gender, profile_id) values ( '2019-02-14', 'Male', 25);
insert into children  (birth_date, gender, profile_id) values ( '2010-03-16', 'Male', 5);
insert into children  (birth_date, gender, profile_id) values ( '2017-07-22', 'Male', 98);
insert into children  (birth_date, gender, profile_id) values ( '2016-11-10', 'Male', 88);
insert into children  (birth_date, gender, profile_id) values ( '2018-04-27', 'Male', 87);
insert into children  (birth_date, gender, profile_id) values ( '2015-11-14', 'Female', 86);
insert into children  (birth_date, gender, profile_id) values ( '2017-08-13', 'Female', 21);
insert into children  (birth_date, gender, profile_id) values ( '2019-05-15', 'Female', 43);
insert into children  (birth_date, gender, profile_id) values ( '2010-10-29', 'Female', 88);
insert into children  (birth_date, gender, profile_id) values ( '2017-06-22', 'Female', 97);
insert into children  (birth_date, gender, profile_id) values ( '2014-09-10', 'Female', 51);
insert into children  (birth_date, gender, profile_id) values ( '2010-09-21', 'Male', 96);
insert into children  (birth_date, gender, profile_id) values ( '2017-10-13', 'Male', 78);
insert into children  (birth_date, gender, profile_id) values ( '2015-05-02', 'Male', 93);
insert into children  (birth_date, gender, profile_id) values ( '2015-02-05', 'Female', 100);
insert into children  (birth_date, gender, profile_id) values ( '2011-10-18', 'Female', 32);
insert into children  (birth_date, gender, profile_id) values ( '2019-09-03', 'Female', 76);
insert into children  (birth_date, gender, profile_id) values ( '2013-10-01', 'Male', 10);
insert into children  (birth_date, gender, profile_id) values ( '2014-11-05', 'Male', 60);
insert into children  (birth_date, gender, profile_id) values ( '2018-11-30', 'Male', 100);
insert into children  (birth_date, gender, profile_id) values ( '2010-03-01', 'Male', 39);
insert into children  (birth_date, gender, profile_id) values ( '2012-03-02', 'Male', 56);
insert into children  (birth_date, gender, profile_id) values ( '2019-09-04', 'Female', 4);
insert into children  (birth_date, gender, profile_id) values ( '2017-08-13', 'Female', 19);
insert into children  (birth_date, gender, profile_id) values ( '2016-12-22', 'Female', 55);
insert into children  (birth_date, gender, profile_id) values ( '2014-09-03', 'Male', 89);
insert into children  (birth_date, gender, profile_id) values ( '2015-12-13', 'Female', 40);
insert into children  (birth_date, gender, profile_id) values ( '2019-10-17', 'Female', 6);
insert into children  (birth_date, gender, profile_id) values ( '2010-11-11', 'Male', 40);
insert into children  (birth_date, gender, profile_id) values ( '2019-04-17', 'Female', 33);
insert into children  (birth_date, gender, profile_id) values ( '2011-11-07', 'Male', 8);


insert into hobbies (hobby) values ( 'Gardening');
insert into hobbies (hobby) values ( 'Cooking');
insert into hobbies (hobby) values ( 'Learning');
insert into hobbies (hobby) values ( 'exercising');
insert into hobbies (hobby) values ( 'Writing');
insert into hobbies (hobby) values ( 'Dance');
insert into hobbies (hobby) values ( 'Photography');
insert into hobbies (hobby) values ( 'Hiking');
insert into hobbies (hobby) values ( 'Drawing/Painting');
insert into hobbies (hobby) values ( 'Hunting');
insert into hobbies (hobby) values ( 'Sewing');
insert into hobbies (hobby) values ( 'Sports/Extreme Sports');
insert into hobbies (hobby) values ( 'Programming');
insert into hobbies (hobby) values ( 'Biking');
insert into hobbies (hobby) values ( 'Camping');
insert into hobbies (hobby) values ( 'Wood Working');
insert into hobbies (hobby) values ( 'Pottery');
insert into hobbies (hobby) values ( 'Exercise');
insert into hobbies (hobby) values ( 'Traveling');
insert into hobbies (hobby) values ( 'Playing Instruments');
insert into hobbies (hobby) values ( 'Volunteer Work');

insert into traits (trait) values ( 'Giving');
insert into traits (trait) values ( 'Clever');
insert into traits (trait) values ( 'Ambitious');
insert into traits (trait) values ( 'Honest');
insert into traits (trait) values ( 'Easygoing');
insert into traits (trait) values ( 'Quiet');
insert into traits (trait) values ( 'Insightful');
insert into traits (trait) values ( 'Devoted');
insert into traits (trait) values ( 'Confident');
insert into traits (trait) values ( 'Adventurous');
insert into traits (trait) values ( 'Focused');
insert into traits (trait) values ( 'Friendly');
insert into traits (trait) values ( 'Open minded');
insert into traits (trait) values ( 'Dependable');
insert into traits (trait) values ( 'Generous');
insert into traits (trait) values ( 'Wise');
insert into traits (trait) values ( 'Strong');
insert into traits (trait) values ( 'Loyal');
insert into traits (trait) values ( 'Hard Working');
insert into traits (trait) values ( 'Creative');











insert into hobby_profile (hobby_id, profile_id) values (1, 34);
insert into hobby_profile (hobby_id, profile_id) values (5, 100);
insert into hobby_profile (hobby_id, profile_id) values (1, 55);
insert into hobby_profile (hobby_id, profile_id) values (6, 73);
insert into hobby_profile (hobby_id, profile_id) values (4, 1);
insert into hobby_profile (hobby_id, profile_id) values (7, 31);
insert into hobby_profile (hobby_id, profile_id) values (8, 20);
insert into hobby_profile (hobby_id, profile_id) values (2, 4);
insert into hobby_profile (hobby_id, profile_id) values (8, 23);
insert into hobby_profile (hobby_id, profile_id) values (7, 12);
insert into hobby_profile (hobby_id, profile_id) values (7, 71);
insert into hobby_profile (hobby_id, profile_id) values (8, 29);
insert into hobby_profile (hobby_id, profile_id) values (7, 52);
insert into hobby_profile (hobby_id, profile_id) values (6, 98);
insert into hobby_profile (hobby_id, profile_id) values (3, 29);
insert into hobby_profile (hobby_id, profile_id) values (7, 14);
insert into hobby_profile (hobby_id, profile_id) values (2, 42);
insert into hobby_profile (hobby_id, profile_id) values (8, 7);
insert into hobby_profile (hobby_id, profile_id) values (3, 1);
insert into hobby_profile (hobby_id, profile_id) values (7, 46);
insert into hobby_profile (hobby_id, profile_id) values (8, 94);
insert into hobby_profile (hobby_id, profile_id) values (4, 33);
insert into hobby_profile (hobby_id, profile_id) values (2, 75);
insert into hobby_profile (hobby_id, profile_id) values (3, 61);
insert into hobby_profile (hobby_id, profile_id) values (3, 85);
insert into hobby_profile (hobby_id, profile_id) values (8, 42);
insert into hobby_profile (hobby_id, profile_id) values (6, 100);
insert into hobby_profile (hobby_id, profile_id) values (7, 34);
insert into hobby_profile (hobby_id, profile_id) values (1, 29);
insert into hobby_profile (hobby_id, profile_id) values (8, 5);
insert into hobby_profile (hobby_id, profile_id) values (8, 92);
insert into hobby_profile (hobby_id, profile_id) values (8, 65);
insert into hobby_profile (hobby_id, profile_id) values (7, 27);
insert into hobby_profile (hobby_id, profile_id) values (7, 44);
insert into hobby_profile (hobby_id, profile_id) values (5, 99);
insert into hobby_profile (hobby_id, profile_id) values (6, 17);
insert into hobby_profile (hobby_id, profile_id) values (4, 11);
insert into hobby_profile (hobby_id, profile_id) values (2, 17);
insert into hobby_profile (hobby_id, profile_id) values (1, 32);
insert into hobby_profile (hobby_id, profile_id) values (4, 69);
insert into hobby_profile (hobby_id, profile_id) values (6, 7);
insert into hobby_profile (hobby_id, profile_id) values (6, 30);
insert into hobby_profile (hobby_id, profile_id) values (4, 38);
insert into hobby_profile (hobby_id, profile_id) values (5, 16);
insert into hobby_profile (hobby_id, profile_id) values (1, 82);
insert into hobby_profile (hobby_id, profile_id) values (1, 63);
insert into hobby_profile (hobby_id, profile_id) values (1, 9);
insert into hobby_profile (hobby_id, profile_id) values (8, 19);
insert into hobby_profile (hobby_id, profile_id) values (1, 4);
insert into hobby_profile (hobby_id, profile_id) values (2, 68);
insert into hobby_profile (hobby_id, profile_id) values (7, 7);
insert into hobby_profile (hobby_id, profile_id) values (1, 83);
insert into hobby_profile (hobby_id, profile_id) values (3, 96);
insert into hobby_profile (hobby_id, profile_id) values (2, 41);
insert into hobby_profile (hobby_id, profile_id) values (1, 64);
insert into hobby_profile (hobby_id, profile_id) values (5, 97);
insert into hobby_profile (hobby_id, profile_id) values (7, 31);
insert into hobby_profile (hobby_id, profile_id) values (6, 4);
insert into hobby_profile (hobby_id, profile_id) values (8, 9);
insert into hobby_profile (hobby_id, profile_id) values (6, 48);
insert into hobby_profile (hobby_id, profile_id) values (5, 80);
insert into hobby_profile (hobby_id, profile_id) values (6, 34);
insert into hobby_profile (hobby_id, profile_id) values (5, 82);
insert into hobby_profile (hobby_id, profile_id) values (6, 86);
insert into hobby_profile (hobby_id, profile_id) values (8, 91);
insert into hobby_profile (hobby_id, profile_id) values (7, 99);
insert into hobby_profile (hobby_id, profile_id) values (6, 38);
insert into hobby_profile (hobby_id, profile_id) values (2, 23);
insert into hobby_profile (hobby_id, profile_id) values (2, 98);
insert into hobby_profile (hobby_id, profile_id) values (7, 29);
insert into hobby_profile (hobby_id, profile_id) values (6, 33);
insert into hobby_profile (hobby_id, profile_id) values (2, 93);
insert into hobby_profile (hobby_id, profile_id) values (5, 76);
insert into hobby_profile (hobby_id, profile_id) values (6, 73);
insert into hobby_profile (hobby_id, profile_id) values (6, 22);
insert into hobby_profile (hobby_id, profile_id) values (4, 22);
insert into hobby_profile (hobby_id, profile_id) values (2, 58);
insert into hobby_profile (hobby_id, profile_id) values (4, 36);
insert into hobby_profile (hobby_id, profile_id) values (7, 1);
insert into hobby_profile (hobby_id, profile_id) values (2, 94);
insert into hobby_profile (hobby_id, profile_id) values (7, 75);
insert into hobby_profile (hobby_id, profile_id) values (5, 49);
insert into hobby_profile (hobby_id, profile_id) values (1, 73);
insert into hobby_profile (hobby_id, profile_id) values (5, 22);
insert into hobby_profile (hobby_id, profile_id) values (4, 86);
insert into hobby_profile (hobby_id, profile_id) values (6, 10);
insert into hobby_profile (hobby_id, profile_id) values (8, 54);
insert into hobby_profile (hobby_id, profile_id) values (2, 45);
insert into hobby_profile (hobby_id, profile_id) values (4, 62);
insert into hobby_profile (hobby_id, profile_id) values (8, 89);
insert into hobby_profile (hobby_id, profile_id) values (6, 3);
insert into hobby_profile (hobby_id, profile_id) values (2, 62);
insert into hobby_profile (hobby_id, profile_id) values (5, 69);
insert into hobby_profile (hobby_id, profile_id) values (7, 52);
insert into hobby_profile (hobby_id, profile_id) values (6, 66);
insert into hobby_profile (hobby_id, profile_id) values (1, 95);
insert into hobby_profile (hobby_id, profile_id) values (1, 12);
insert into hobby_profile (hobby_id, profile_id) values (7, 80);
insert into hobby_profile (hobby_id, profile_id) values (3, 73);
insert into hobby_profile (hobby_id, profile_id) values (3, 58);



insert into traits (id, trait) values (1, 'quiet');
insert into traits (id, trait) values (2, 'talkative');
insert into traits (id, trait) values (3, 'easy-going');
insert into traits (id, trait) values (4, 'extroverted');
insert into traits (id, trait) values (5, 'introverted');
insert into traits (id, trait) values (6, 'quiet');
insert into traits (id, trait) values (7, 'social');


insert into profile_trait (profile_id, trait_id) values (2, 6);
insert into profile_trait (profile_id, trait_id) values (99, 7);
insert into profile_trait (profile_id, trait_id) values (55, 4);
insert into profile_trait (profile_id, trait_id) values (63, 4);
insert into profile_trait (profile_id, trait_id) values (33, 4);
insert into profile_trait (profile_id, trait_id) values (24, 6);
insert into profile_trait (profile_id, trait_id) values (26, 3);
insert into profile_trait (profile_id, trait_id) values (37, 2);
insert into profile_trait (profile_id, trait_id) values (5, 4);
insert into profile_trait (profile_id, trait_id) values (87, 5);
insert into profile_trait (profile_id, trait_id) values (1, 3);
insert into profile_trait (profile_id, trait_id) values (74, 1);
insert into profile_trait (profile_id, trait_id) values (100, 6);
insert into profile_trait (profile_id, trait_id) values (64, 1);
insert into profile_trait (profile_id, trait_id) values (38, 5);
insert into profile_trait (profile_id, trait_id) values (84, 6);
insert into profile_trait (profile_id, trait_id) values (76, 2);
insert into profile_trait (profile_id, trait_id) values (23, 3);
insert into profile_trait (profile_id, trait_id) values (3, 3);
insert into profile_trait (profile_id, trait_id) values (49, 7);
insert into profile_trait (profile_id, trait_id) values (6, 6);
insert into profile_trait (profile_id, trait_id) values (8, 2);
insert into profile_trait (profile_id, trait_id) values (33, 2);
insert into profile_trait (profile_id, trait_id) values (60, 4);
insert into profile_trait (profile_id, trait_id) values (36, 3);
insert into profile_trait (profile_id, trait_id) values (95, 4);
insert into profile_trait (profile_id, trait_id) values (79, 4);
insert into profile_trait (profile_id, trait_id) values (12, 1);
insert into profile_trait (profile_id, trait_id) values (24, 6);
insert into profile_trait (profile_id, trait_id) values (48, 5);
insert into profile_trait (profile_id, trait_id) values (11, 2);
insert into profile_trait (profile_id, trait_id) values (56, 1);
insert into profile_trait (profile_id, trait_id) values (91, 5);
insert into profile_trait (profile_id, trait_id) values (22, 1);
insert into profile_trait (profile_id, trait_id) values (98, 7);
insert into profile_trait (profile_id, trait_id) values (14, 1);
insert into profile_trait (profile_id, trait_id) values (57, 1);
insert into profile_trait (profile_id, trait_id) values (69, 6);
insert into profile_trait (profile_id, trait_id) values (44, 1);
insert into profile_trait (profile_id, trait_id) values (83, 7);
insert into profile_trait (profile_id, trait_id) values (10, 3);
insert into profile_trait (profile_id, trait_id) values (61, 2);
insert into profile_trait (profile_id, trait_id) values (58, 4);
insert into profile_trait (profile_id, trait_id) values (70, 7);
insert into profile_trait (profile_id, trait_id) values (82, 7);
insert into profile_trait (profile_id, trait_id) values (36, 7);
insert into profile_trait (profile_id, trait_id) values (80, 2);
insert into profile_trait (profile_id, trait_id) values (52, 2);
insert into profile_trait (profile_id, trait_id) values (51, 3);
insert into profile_trait (profile_id, trait_id) values (21, 6);
insert into profile_trait (profile_id, trait_id) values (23, 1);
insert into profile_trait (profile_id, trait_id) values (47, 3);
insert into profile_trait (profile_id, trait_id) values (51, 5);
insert into profile_trait (profile_id, trait_id) values (21, 2);
insert into profile_trait (profile_id, trait_id) values (65, 6);
insert into profile_trait (profile_id, trait_id) values (87, 3);
insert into profile_trait (profile_id, trait_id) values (60, 3);
insert into profile_trait (profile_id, trait_id) values (11, 3);
insert into profile_trait (profile_id, trait_id) values (17, 6);
insert into profile_trait (profile_id, trait_id) values (86, 2);
insert into profile_trait (profile_id, trait_id) values (77, 5);
insert into profile_trait (profile_id, trait_id) values (29, 2);
insert into profile_trait (profile_id, trait_id) values (40, 6);
insert into profile_trait (profile_id, trait_id) values (45, 5);
insert into profile_trait (profile_id, trait_id) values (7, 7);
insert into profile_trait (profile_id, trait_id) values (91, 4);
insert into profile_trait (profile_id, trait_id) values (9, 1);
insert into profile_trait (profile_id, trait_id) values (82, 1);
insert into profile_trait (profile_id, trait_id) values (29, 3);
insert into profile_trait (profile_id, trait_id) values (61, 2);
insert into profile_trait (profile_id, trait_id) values (89, 7);
insert into profile_trait (profile_id, trait_id) values (10, 5);
insert into profile_trait (profile_id, trait_id) values (66, 3);
insert into profile_trait (profile_id, trait_id) values (80, 5);
insert into profile_trait (profile_id, trait_id) values (51, 7);
insert into profile_trait (profile_id, trait_id) values (48, 4);
insert into profile_trait (profile_id, trait_id) values (84, 7);
insert into profile_trait (profile_id, trait_id) values (12, 2);
insert into profile_trait (profile_id, trait_id) values (68, 5);
insert into profile_trait (profile_id, trait_id) values (95, 6);
insert into profile_trait (profile_id, trait_id) values (78, 5);
insert into profile_trait (profile_id, trait_id) values (84, 4);
insert into profile_trait (profile_id, trait_id) values (46, 4);
insert into profile_trait (profile_id, trait_id) values (21, 2);
insert into profile_trait (profile_id, trait_id) values (61, 3);
insert into profile_trait (profile_id, trait_id) values (98, 2);
insert into profile_trait (profile_id, trait_id) values (72, 3);
insert into profile_trait (profile_id, trait_id) values (64, 3);
insert into profile_trait (profile_id, trait_id) values (21, 2);
insert into profile_trait (profile_id, trait_id) values (60, 2);
insert into profile_trait (profile_id, trait_id) values (84, 5);
insert into profile_trait (profile_id, trait_id) values (15, 4);
insert into profile_trait (profile_id, trait_id) values (48, 2);
insert into profile_trait (profile_id, trait_id) values (58, 1);
insert into profile_trait (profile_id, trait_id) values (29, 6);
insert into profile_trait (profile_id, trait_id) values (59, 2);
insert into profile_trait (profile_id, trait_id) values (10, 2);
insert into profile_trait (profile_id, trait_id) values (28, 4);
insert into profile_trait (profile_id, trait_id) values (52, 5);
insert into profile_trait (profile_id, trait_id) values (52, 2);



insert into locations (id, city, country, state) values (1, 'Salt Lake City', 'United States', 'UT');
insert into locations (id, city, country, state) values (2, 'San Antonio', 'United States', 'TX');
insert into locations (id, city, country, state) values (3, 'Charlotte', 'United States', 'NC');
insert into locations (id, city, country, state) values (4, 'Miami', 'United States', 'FL');
insert into locations (id, city, country, state) values (5, 'Honolulu', 'United States', 'HI');


insert into location_profile (profile_id, location_id) values (13, 2);
insert into location_profile (profile_id, location_id) values (78, 1);
insert into location_profile (profile_id, location_id) values (60, 4);
insert into location_profile (profile_id, location_id) values (52, 3);
insert into location_profile (profile_id, location_id) values (71, 5);
insert into location_profile (profile_id, location_id) values (33, 1);
insert into location_profile (profile_id, location_id) values (98, 5);
insert into location_profile (profile_id, location_id) values (56, 4);
insert into location_profile (profile_id, location_id) values (98, 3);
insert into location_profile (profile_id, location_id) values (15, 4);
insert into location_profile (profile_id, location_id) values (23, 2);
insert into location_profile (profile_id, location_id) values (19, 2);
insert into location_profile (profile_id, location_id) values (1, 1);
insert into location_profile (profile_id, location_id) values (54, 5);
insert into location_profile (profile_id, location_id) values (5, 3);
insert into location_profile (profile_id, location_id) values (77, 2);
insert into location_profile (profile_id, location_id) values (68, 3);
insert into location_profile (profile_id, location_id) values (53, 1);
insert into location_profile (profile_id, location_id) values (86, 5);
insert into location_profile (profile_id, location_id) values (89, 3);
insert into location_profile (profile_id, location_id) values (84, 3);
insert into location_profile (profile_id, location_id) values (79, 5);
insert into location_profile (profile_id, location_id) values (6, 5);
insert into location_profile (profile_id, location_id) values (61, 1);
insert into location_profile (profile_id, location_id) values (56, 2);
insert into location_profile (profile_id, location_id) values (20, 3);
insert into location_profile (profile_id, location_id) values (56, 5);
insert into location_profile (profile_id, location_id) values (85, 2);
insert into location_profile (profile_id, location_id) values (33, 1);
insert into location_profile (profile_id, location_id) values (26, 2);
insert into location_profile (profile_id, location_id) values (20, 5);
insert into location_profile (profile_id, location_id) values (53, 3);
insert into location_profile (profile_id, location_id) values (73, 5);
insert into location_profile (profile_id, location_id) values (36, 1);
insert into location_profile (profile_id, location_id) values (2, 2);
insert into location_profile (profile_id, location_id) values (26, 4);
insert into location_profile (profile_id, location_id) values (92, 2);
insert into location_profile (profile_id, location_id) values (28, 4);
insert into location_profile (profile_id, location_id) values (83, 3);
insert into location_profile (profile_id, location_id) values (91, 3);
insert into location_profile (profile_id, location_id) values (38, 5);
insert into location_profile (profile_id, location_id) values (37, 1);
insert into location_profile (profile_id, location_id) values (9, 1);
insert into location_profile (profile_id, location_id) values (90, 5);
insert into location_profile (profile_id, location_id) values (63, 2);
insert into location_profile (profile_id, location_id) values (67, 4);
insert into location_profile (profile_id, location_id) values (39, 5);
insert into location_profile (profile_id, location_id) values (70, 1);
insert into location_profile (profile_id, location_id) values (49, 2);
insert into location_profile (profile_id, location_id) values (55, 1);
insert into location_profile (profile_id, location_id) values (40, 1);
insert into location_profile (profile_id, location_id) values (54, 1);
insert into location_profile (profile_id, location_id) values (84, 3);
insert into location_profile (profile_id, location_id) values (20, 2);
insert into location_profile (profile_id, location_id) values (78, 4);
insert into location_profile (profile_id, location_id) values (62, 5);
insert into location_profile (profile_id, location_id) values (74, 1);
insert into location_profile (profile_id, location_id) values (69, 1);
insert into location_profile (profile_id, location_id) values (62, 1);
insert into location_profile (profile_id, location_id) values (75, 2);
insert into location_profile (profile_id, location_id) values (49, 2);
insert into location_profile (profile_id, location_id) values (71, 4);
insert into location_profile (profile_id, location_id) values (45, 3);
insert into location_profile (profile_id, location_id) values (77, 5);
insert into location_profile (profile_id, location_id) values (76, 2);
insert into location_profile (profile_id, location_id) values (81, 2);
insert into location_profile (profile_id, location_id) values (47, 4);
insert into location_profile (profile_id, location_id) values (29, 2);
insert into location_profile (profile_id, location_id) values (23, 2);
insert into location_profile (profile_id, location_id) values (58, 3);
insert into location_profile (profile_id, location_id) values (100, 5);
insert into location_profile (profile_id, location_id) values (74, 4);
insert into location_profile (profile_id, location_id) values (34, 1);
insert into location_profile (profile_id, location_id) values (4, 4);
insert into location_profile (profile_id, location_id) values (75, 2);
insert into location_profile (profile_id, location_id) values (2, 2);
insert into location_profile (profile_id, location_id) values (90, 1);
insert into location_profile (profile_id, location_id) values (75, 4);
insert into location_profile (profile_id, location_id) values (80, 5);
insert into location_profile (profile_id, location_id) values (59, 2);
insert into location_profile (profile_id, location_id) values (19, 3);
insert into location_profile (profile_id, location_id) values (4, 5);
insert into location_profile (profile_id, location_id) values (31, 4);
insert into location_profile (profile_id, location_id) values (34, 5);
insert into location_profile (profile_id, location_id) values (8, 2);
insert into location_profile (profile_id, location_id) values (22, 2);
insert into location_profile (profile_id, location_id) values (67, 4);
insert into location_profile (profile_id, location_id) values (63, 3);
insert into location_profile (profile_id, location_id) values (19, 2);
insert into location_profile (profile_id, location_id) values (14, 1);
insert into location_profile (profile_id, location_id) values (34, 2);
insert into location_profile (profile_id, location_id) values (53, 1);
insert into location_profile (profile_id, location_id) values (22, 1);
insert into location_profile (profile_id, location_id) values (69, 5);
insert into location_profile (profile_id, location_id) values (74, 5);
insert into location_profile (profile_id, location_id) values (48, 5);
insert into location_profile (profile_id, location_id) values (77, 5);
insert into location_profile (profile_id, location_id) values (5, 5);
insert into location_profile (profile_id, location_id) values (45, 1);
insert into location_profile (profile_id, location_id) values (98, 3);


